map:
    location:   [16.3, 106.72]
    zoom:       6
    overlay:    'modules/map/overlay/geojson/vietnam.geojson'
    cordinates: 'modules/map/overlay/coordinates/coordinates.json'

    template_dir:   'web/templates'
    static_dir:     'web/static'
    icon_path:      null
    
    vega_chart:     'web/static/data/chart.json'

api:
    host:       http://157.245.207.139:8000/api/

database:
    filename:   'modules/database/config/postgresql.ini'
    section:    'postgresql'